name: Test and Build Reports Scheduler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

    # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: '1.0.0-beta1'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal -Dbuild.version_qualifier=beta1 -Dbuild.snapshot=false

      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/common-utils'
          ref: '1.0.0-beta1'
          path: common-utils
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-beta1

      # dependencies: job-scheduler
      - name: Checkout job-scheduler
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/job-scheduler'
          ref: '1.0.0-beta1'
          path: job-scheduler
      - name: Build job-scheduler
        working-directory: ./job-scheduler
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-beta1 -Dbuild.snapshot=false

      # reports-scheduler
      - name: Checkout Reports Scheduler
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          cd reports-scheduler
          ./gradlew build -Dopensearch.version=1.0.0-beta1

      - name: Create Artifact Path
        run: |
          mkdir -p reports-scheduler-builds
          cp -r ./reports-scheduler/build/distributions/*.zip reports-scheduler-builds/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: reports-scheduler
          path: reports-scheduler-builds
